version: 2.1

setup: true

orbs:
  dynamic: bjd2385/dynamic-continuation@3.0.14

workflows:
  version: 2

  default:
    jobs:
      - dynamic/continue:
          context: orb-publishing
          modules: |
            scripts
