version: 2.1

orbs:
  shellcheck: circleci/shellcheck@3.1.1

executors:
  default:
    docker:
      - image: cimg/base:stable

workflows:
  version: 2

  scripts:
    jobs:
      - shellcheck/check:
          dir: ./scripts
          filters:
            branches:
              ignore: master
